export const CAMPOS_AVISO = {
  cliente: "Cliente",
  descripcion: "Descripción",
  ubicacionTecnica: "Ubicación Técnica",
  numeroAviso: "N° Aviso",
  ordenVenta: "Orden de Venta",
  centroCosto: "Centro de Costo",
  prioridad: "Prioridad",
  fechaAtencion: "Fecha Atención",
  tipoMantenimiento: "Tipo de Mantenimiento",
  producto: "Producto",
  direccionAtencion: "Dirección de Atención",
  solicitante: "Solicitante",
  supervisorAsignado: "Supervisor Asignado",
  estadoAviso: "Estado del Aviso",
  nombreContacto: "Nombre de Contacto",
  correoContacto: "Correo de Contacto",
  numeroContacto: "Número de Contacto",
  descripcionResumida: "Descripción Resumida",
  documentos: "Documentos Adjuntos",
  documentoFinal: "Documento Final",
};
